/**
 * @fileoverview Check if Tailwind CSS classnames have the correct prefix.
 * @author no-custom-classname
 */
'use strict';

const docsUrl = require('../util/docsUrl');
const defaultGroups = require('../config/groups').groups;
const customConfig = require('../util/customConfig');
const astUtil = require('../util/ast');
const groupUtil = require('../util/groupMethods');
const getOption = require('../util/settings');
const parserUtil = require('../util/parser');
const getClassnamesFromCSS = require('../util/cssFiles');
const createContextFallback = require('tailwindcss/lib/lib/setupContextUtils').createContext;
const generated = require('../util/generated');
const escapeRegex = require('../util/regex').escapeRegex;

//------------------------------------------------------------------------------
// Rule Definition
//------------------------------------------------------------------------------

// Predefine message for use in context.report conditional.
// messageId will still be usable in tests.
const MISSING_PREFIX_CLASSNAME_MSG = `Classname '{{classname}}' is missing the Tailwind prefix '{{prefix}}'.`;

// Group/peer names can be arbitrarily named and are not
// generated by generateRules. Using a custom regexp to
// validate these avoids false reports.
const getGroupNameRegex = (prefix = '') =>
  new RegExp(`^${escapeRegex(prefix)}(group|peer)\/[\\w\\$\\#\\@\\%\\^\\&\\*\\_\\-]+$`, 'i');

const contextFallbackCache = new WeakMap();

module.exports = {
  meta: {
    docs: {
      description: 'Check if Tailwind CSS classnames have the correct prefix.',
      category: 'Best Practices',
      recommended: false,
      url: docsUrl('tailwind-prefix'),
    },
    messages: {
      missingPrefixClassnameDetected: MISSING_PREFIX_CLASSNAME_MSG,
    },
    fixable: 'code',
    schema: [
      {
        type: 'object',
        properties: {
          callees: {
            type: 'array',
            items: { type: 'string', minLength: 0 },
            uniqueItems: true,
          },
          ignoredKeys: {
            type: 'array',
            items: { type: 'string', minLength: 0 },
            uniqueItems: true,
          },
          config: {
            // returned from `loadConfig()` utility
            type: ['string', 'object'],
          },
          cssFiles: {
            type: 'array',
            items: { type: 'string', minLength: 0 },
            uniqueItems: true,
          },
          cssFilesRefreshRate: {
            type: 'number',
            // default: 5_000,
          },
          tags: {
            type: 'array',
            items: { type: 'string', minLength: 0 },
            uniqueItems: true,
          },
          whitelist: {
            type: 'array',
            items: { type: 'string', minLength: 0 },
            uniqueItems: true,
          },
        },
      },
    ],
  },

  create: function (context) {
    const callees = getOption(context, 'callees');
    const ignoredKeys = getOption(context, 'ignoredKeys');
    const skipClassAttribute = getOption(context, 'skipClassAttribute');
    const tags = getOption(context, 'tags');
    const twConfig = getOption(context, 'config');
    const cssFiles = getOption(context, 'cssFiles');
    const cssFilesRefreshRate = getOption(context, 'cssFilesRefreshRate');
    const whitelist = getOption(context, 'whitelist');
    const classRegex = getOption(context, 'classRegex');

    const mergedConfig = customConfig.resolve(twConfig);
    const contextFallback = // Set the created contextFallback in the cache if it does not exist yet.
      (
        contextFallbackCache.has(mergedConfig)
          ? contextFallbackCache
          : contextFallbackCache.set(mergedConfig, createContextFallback(mergedConfig))
      ).get(mergedConfig);

    //----------------------------------------------------------------------
    // Helpers
    //----------------------------------------------------------------------

    // Init assets before sorting
    const groups = groupUtil.getGroups(defaultGroups, mergedConfig);
    const classnamesFromFiles = getClassnamesFromCSS(cssFiles, cssFilesRefreshRate);
    const groupNameRegex = getGroupNameRegex(mergedConfig.prefix);

    /**
     * Recursive function crawling into child nodes
     * @param {ASTNode} node The root node of the current parsing
     * @param {ASTNode} arg The child node of node
     * @returns {void}
     */
    const parseForMissingPrefix = (node, arg = null) => {
      let originalClassNamesValue = null;
      let start = null;
      let end = null;
      let prefix = '';
      let suffix = '';
      if (arg === null) {
        originalClassNamesValue = astUtil.extractValueFromNode(node);
        const range = astUtil.extractRangeFromNode(node);
        if (node.type === 'TextAttribute') {
          start = range[0];
          end = range[1];
        } else {
          start = range[0] + 1;
          end = range[1] - 1;
        }
      } else {
        switch (arg.type) {
          case 'Identifier':
            return;
          case 'TemplateLiteral':
            arg.expressions.forEach((exp) => {
              parseForMissingPrefix(node, exp);
            });
            arg.quasis.forEach((quasis) => {
              parseForMissingPrefix(node, quasis);
            });
            return;
          case 'ConditionalExpression':
            parseForMissingPrefix(node, arg.consequent);
            parseForMissingPrefix(node, arg.alternate);
            return;
          case 'LogicalExpression':
            parseForMissingPrefix(node, arg.right);
            return;
          case 'ArrayExpression':
            arg.elements.forEach((el) => {
              parseForMissingPrefix(node, el);
            });
            return;
          case 'ObjectExpression':
            const isUsedByClassNamesPlugin = node.callee && node.callee.name === 'classnames';
            const isVue = node.key && node.key.type === 'VDirectiveKey';
            // skip ignored keys
            arg.properties.forEach((prop) => {
              if (!ignoredKeys.includes(prop.key.name)) {
                const propVal = isUsedByClassNamesPlugin || isVue ? prop.key : prop.value;
                return parseForMissingPrefix(prop, propVal);
              }
            });
            return;
          case 'Property':
            parseForMissingPrefix(node, arg.key);
            break;
          case 'Literal':
            originalClassNamesValue = arg.value;
            start = arg.range[0] + 1;
            end = arg.range[1] - 1;
            break;
          case 'TemplateElement':
            originalClassNamesValue = arg.value.raw;
            if (originalClassNamesValue === '') {
              return;
            }
            start = arg.range[0];
            end = arg.range[1];
            // https://github.com/eslint/eslint/issues/13360
            // The problem is that range computation includes the backticks (`test`)
            // but value.raw does not include them, so there is a mismatch.
            // start/end does not include the backticks, therefore it matches value.raw.
            const txt = context.getSourceCode().getText(arg);
            prefix = astUtil.getTemplateElementPrefix(txt, originalClassNamesValue);
            suffix = astUtil.getTemplateElementSuffix(txt, originalClassNamesValue);
            originalClassNamesValue = astUtil.getTemplateElementBody(txt, prefix, suffix);
            break;
        }
      }

      let { classNames, whitespaces, headSpace, tailSpace } =
        astUtil.extractClassnamesFromValue(originalClassNamesValue);

      if (!classNames.length) {
        // skip if no classnames
        return;
      }

      const prefixedClassNames = [...classNames];
      const partialMessage = [];
      let hasMissingPrefixClassNames = false;

      classNames.forEach((className, index) => {
        // already use prefix
        if (generated(className, contextFallback).length) {
          return;
        }
        const idx = groupUtil.getGroupIndex(className, groups, mergedConfig.separator);
        if (idx >= 0) {
          return;
        }
        // already in css files
        const fromFilesIdx = groupUtil.getGroupIndex(className, classnamesFromFiles, mergedConfig.separator);
        if (fromFilesIdx >= 0) {
          return;
        }
        if (groupNameRegex.test(className)) {
          return;
        }

        // add prefix to className
        let prefixedClassName;
        if (className[0] === '-') {
          prefixedClassName = `-${mergedConfig.prefix}${className.slice(1)}`;
        } else if (className.includes(':-')) {
          const [first, rest] = className.split(':-');
          prefixedClassName = `${first}:-${mergedConfig.prefix}${rest}`;
        } else if (className.includes(':')) {
          const classNameParts = className.split(':');
          const lastPart = classNameParts.pop();
          prefixedClassName = `${classNameParts.join(':')}:${mergedConfig.prefix}${lastPart}`;
        } else {
          prefixedClassName = `${mergedConfig.prefix}${className}`;
        }

        // check if prefixedClassName is valid or not
        if (!generated(prefixedClassName, contextFallback).length) {
          return;
        }

        prefixedClassNames[index] = prefixedClassName;
        partialMessage.push(className);
        hasMissingPrefixClassNames = true;
      });

      if (hasMissingPrefixClassNames) {
        let validatedClassNamesValue = '';
        for (let i = 0; i < prefixedClassNames.length; i++) {
          const w = whitespaces[i] ?? '';
          const cls = prefixedClassNames[i];
          validatedClassNamesValue += headSpace ? `${w}${cls}` : `${cls}${w}`;
          if (headSpace && tailSpace && i === prefixedClassNames.length - 1) {
            validatedClassNamesValue += whitespaces[whitespaces.length - 1] ?? '';
          }
        }

        validatedClassNamesValue = prefix + validatedClassNamesValue + suffix;

        context.report({
          node,
          messageId: 'missingPrefixClassnameDetected',
          data: {
            classname: partialMessage.join(', '),
            prefix: mergedConfig.prefix,
          },
          fix(fixer) {
            // 使用 replaceTextRange 进行修复
            return fixer.replaceTextRange([start, end], validatedClassNamesValue);
          },
        });
      }
    };

    //----------------------------------------------------------------------
    // Public
    //----------------------------------------------------------------------

    const attributeVisitor = function (node) {
      if (mergedConfig.prefix === '') {
        return;
      }
      if (!astUtil.isClassAttribute(node, classRegex) || skipClassAttribute) {
        return;
      }
      if (astUtil.isLiteralAttributeValue(node)) {
        parseForMissingPrefix(node, null);
      } else if (node.value && node.value.type === 'JSXExpressionContainer') {
        parseForMissingPrefix(node, node.value.expression);
      }
    };

    const callExpressionVisitor = function (node) {
      const calleeStr = astUtil.calleeToString(node.callee);
      if (callees.findIndex((name) => calleeStr === name) === -1) {
        return;
      }
      node.arguments.forEach((arg) => {
        parseForMissingPrefix(node, arg);
      });
    };

    const scriptVisitor = {
      JSXAttribute: attributeVisitor,
      TextAttribute: attributeVisitor,
      CallExpression: callExpressionVisitor,
      TaggedTemplateExpression: function (node) {
        if (!tags.includes(node.tag.name)) {
          return;
        }
        parseForMissingPrefix(node, node.quasi);
      },
    };

    const templateVisitor = {
      CallExpression: callExpressionVisitor,
      /*
      Tagged templates inside data bindings
      https://github.com/vuejs/vue/issues/9721
      */
      VAttribute: function (node) {
        switch (true) {
          case !astUtil.isValidVueAttribute(node, classRegex):
            return;
          case astUtil.isVLiteralValue(node):
            parseForMissingPrefix(node, null);
            break;
          case astUtil.isArrayExpression(node):
            node.value.expression.elements.forEach((arg) => {
              parseForMissingPrefix(node, arg);
            });
            break;
          case astUtil.isObjectExpression(node):
            node.value.expression.properties.forEach((prop) => {
              parseForMissingPrefix(node, prop);
            });
            break;
        }
      },
    };

    return parserUtil.defineTemplateBodyVisitor(context, templateVisitor, scriptVisitor);
  },
};
